const Tokenomics = () => {
  return (
    <div
      id="tokenomics"
      className="flex flex-col items-center justify-around gap-4 bg-black p-[10%] md:flex-row md:px-[10%]  lg:h-[125vh]"
    >
      <div className="flex h-fit w-full flex-col items-start justify-center">
        <div className="relative flex w-full flex-row items-end justify-center md:justify-start">
          <p className="font-marker text-4xl font-black">
            TOKENOMICS
            <hr aria-orientation="horizontal" className="my-5" />
          </p>

          <img
            src="images\transparentBg\23bgt.png"
            alt=""
            loading="lazy"
            className="absolute left-[650px] top-[-122px] hidden w-[200px] object-contain lg:block"
          />
        </div>
        <div className="mt-[2rem] grid w-full grid-cols-1 gap-y-0 lg:grid-cols-2 lg:gap-y-[20%]">
          <div className="tokenomics">
            <img
              src="/Icons/RaffleTicket.svg"
              loading="lazy"
              className="hidden w-[128px] object-contain md:block"
              alt=""
            />
            <div className="flex flex-col py-2 px-3">
              <p className="text-2xl font-black">LIFETIME TICKET FOR REWARDS</p>
              <p className="text-lg font-light">
                1 BULL = 1 lifetime ticket to the weekly reward got from Bitcoin
                Mining
              </p>
            </div>
          </div>
          <div className="tokenomics">
            <img
              src="/Icons/Networking.svg"
              loading="lazy"
              className="hidden w-[128px] object-contain md:block"
              alt=""
            />
            <div className="flex flex-col py-2 px-3">
              <p className="text-2xl font-black">RAISING CAPITAL</p>
              <p className="text-lg font-light">
                Once all 4999 bulls are minted, the capital raised from minting
                will be distributed in various Node Projects.
              </p>
            </div>
          </div>
          <div className="tokenomics">
            <img
              src="/Icons/RaffleDrawingMachine.svg"
              loading="lazy"
              className="hidden w-[128px] object-contain md:block"
              alt=""
            />
            <div className="flex flex-col py-2 px-3">
              <p className="text-2xl font-black">WEEKLY GIVEAWAY</p>
              <p className="text-lg font-light">
                A weekly node giveaway will be held with the prizes coming from
                the rewards generated by our nodes.
              </p>
            </div>
          </div>
          <div className="tokenomics">
            <img
              src="/Icons/CompoundingIllustration.svg"
              loading="lazy"
              className="hidden w-[128px] object-contain md:block"
              alt=""
            />
            <div className="flex flex-col py-2 px-3">
              <p className="text-2xl font-black">COMPOUNDING REWARDS</p>
              <p className="text-lg font-light">
                50% of all rewards will be compounded, so the giveaway grows
                more and more each week!
              </p>
            </div>
          </div>
          <div className="tokenomics">
            <img
              src="/Icons/BuddySystem.svg"
              loading="lazy"
              className="hidden w-[128px] object-contain md:block"
              alt=""
            />
            <div className="flex flex-col py-2 px-3">
              <p className="text-2xl font-black">BUDDY SYSTEM</p>
              <p className="text-lg font-light">
                If you refer someone to this project, you will get 2% of the
                purchase
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Tokenomics
