const Tokenomics = () => {
  return (
    <div
      id="tokenomics"
      className="flex min-h-[100vh] flex-col items-center justify-around gap-4 bg-cyan-600 p-[10%] md:flex-row md:p-0 md:px-[10%]"
    >
      <div className="flex max-h-fit min-h-[100%] w-full flex-col items-start justify-center">
        <div className="relative flex w-full flex-row items-end justify-center md:justify-start">
          <p className="text-4xl font-black">
            TOKENOMICS
            <hr aria-orientation="horizontal" className="my-5" />
          </p>

          <img
            src="images\transparentBg\23bgt.png"
            alt=""
            loading="lazy"
            className="absolute left-[650px] top-[-122px] hidden w-[200px] object-contain lg:block"
          />
        </div>
        <div className="mt-[2rem] grid w-full grid-cols-1 gap-y-0 lg:grid-cols-2 lg:gap-y-[20%]">
          <div className="tokenomics">
            <img
              src="https://www.nodebears.com/static/media/ticket.779f37ef.png"
              loading="lazy"
              className="hidden w-[128px] object-contain md:block"
              alt=""
            />
            <div className="flex flex-col ">
              <p className="text-2xl font-black">
                LIFETIME TICKET FOR GIVEAWAYS
              </p>
              <p className="text-2xl font-light">
                1 BULL = 1 lifetime ticket to the weekly node giveaway
              </p>
            </div>
          </div>
          <div className="tokenomics">
            <img
              src="https://www.nodebears.com/static/media/raising.f2764e28.png"
              loading="lazy"
              className="hidden w-[128px] object-contain md:block"
              alt=""
            />
            <div className="flex flex-col ">
              <p className="text-2xl font-black">RAISING CAPITAL</p>
              <p className="text-2xl font-light">
                Once all 4999 bulls are minted, the capital raised from minting
                will be distributed in various Node Projects.
              </p>
            </div>
          </div>
          <div className="tokenomics">
            <img
              src="https://www.nodebears.com/static/media/weekly.a89b5668.png"
              loading="lazy"
              className="hidden w-[128px] object-contain md:block"
              alt=""
            />
            <div className="flex flex-col ">
              <p className="text-2xl font-black">WEEKLY GIVEAWAY</p>
              <p className="text-2xl font-light">
                A weekly node giveaway will be held with the prizes coming from
                the rewards generated by our nodes.
              </p>
            </div>
          </div>
          <div className="tokenomics">
            <img
              src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAk8AAAJPCAYAAABlxzBuAAAACXBIWXMAABcSAAAXEgFnn9JSAAAF0WlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNy4xLWMwMDAgNzkuZWRhMmIzZmFjLCAyMDIxLzExLzE3LTE3OjIzOjE5ICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQjIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgMjMuMSAoTWFjaW50b3NoKSIgeG1wOkNyZWF0ZURhdGU9IjIwMjItMDItMjRUMjI6NTk6NDQrMDE6MDAiIHhtcDpNZXRhZGF0YURhdGU9IjIwMjItMDItMjRUMjI6NTk6NDQrMDE6MDAiIHhtcDpNb2RpZnlEYXRlPSIyMDIyLTAyLTI0VDIyOjU5OjQ0KzAxOjAwIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOmZmZTYwMzg3LTAzOWItNGQ3My1iNDZiLTY2YTkwMDA3NTE1YyIgeG1wTU06RG9jdW1lbnRJRD0iYWRvYmU6ZG9jaWQ6cGhvdG9zaG9wOmVmOTFmOGY5LWM3ZjYtNzA0Yi04OTk1LTk3N2NjNTI1NDY0MiIgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOjc3NDA2ODQzLWZiZWQtNDJlOC05OTkxLWZkNjk1MWViOWY1NSIgZGM6Zm9ybWF0PSJpbWFnZS9wbmciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjc3NDA2ODQzLWZiZWQtNDJlOC05OTkxLWZkNjk1MWViOWY1NSIgc3RFdnQ6d2hlbj0iMjAyMi0wMi0yNFQyMjo1OTo0NCswMTowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIDIzLjEgKE1hY2ludG9zaCkiLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmZmZTYwMzg3LTAzOWItNGQ3My1iNDZiLTY2YTkwMDA3NTE1YyIgc3RFdnQ6d2hlbj0iMjAyMi0wMi0yNFQyMjo1OTo0NCswMTowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIDIzLjEgKE1hY2ludG9zaCkiIHN0RXZ0OmNoYW5nZWQ9Ii8iLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3Rvcnk+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+zbok0wAAIMFJREFUeJzt3XmYX3Vh7/HPJIGgEEBwA7Qu2I7WEXDD3vso01ttrVp7r61163rb2tZq7UIgYVUQRRFFEUQRxR1B6g6KcJUBpCIKIj9MflkhCWHLQvZtlvsHA40IZL5kZr7nl9/r9Tw88PCE3/kMS/LmnDPn9IyMjAQAgLGZUnsAAEAnEU8AAAXEEwBAAfEEAFBAPAEAFBBPAAAFxBMAQAHxBABQQDwBABQQTwAABcQTAEAB8QQAUEA8AQAUEE8AAAXEEwBAAfEEAFBAPAEAFBBPAAAFxBMAQAHxBABQQDwBABQQTwAABcQTAEAB8QQAUEA8AQAUEE8AAAXEEwBAgWk1D97T01Pz8ONioLdv+y+i878gAHZ1I/f/QX+7NfJIP7ATjIxM/pfQU+OgDxy8A+JpoLdvrySHjP723CTPTPKMJAck2bfeMgDYaSNJVia5PcniJAuTtJLclOSW/nZra8VtYyKeGmCgt++xSX4vye8neWmSQ5NMrToKACbf5iTXJ7k6yWVJru1vtwbrTvp14qmSgd6+fZL8cZI35L5oml53EQA0zpok305yUZLv97dbWyrvSSKeJt1Ab9/Lkvx9kj9L8piqYwCgc6xM8vkk5/W3W7+sOUQ8TYKB3r5pue8M05FJXjDpAwBg13JZktP7260rahxcPE2ggd6+KUn+MskJSQ6etAMDQHe4LskJ/e3W5ZN5UPE0QQZ6+34/yYeT9E3KAQGge12R5D/6262bJ+Ng4mmcDfT2HZTkY0leN6EHAgC2N5Tk40mO7W+31k/kgcTTOBl9cOVbk5yeZMaEHAQA2JGlSf6hv9363kQdQDyNg4Hevicm+XSSPxr3DwcAHo2zkhzV325tHu8PFk87aaC376VJvprkyeP6wQDAzro5yev6262F4/mhNTpml3kx8EBv39uT/DDCCQCa6HlJfjrQ2/eHtYfsrI4/8zTQ2zc1yRlJ/mWnPwwAmGjDSd7e3259Yjw+zGW7QgO9fbsnuTDJ/xmPPQDApHlff7t13M5+iHgqMPoC368leeW4DQIAJtOZSf6tv9161DFSo2OmTfoRx8HoGadvJnlF7S0AwKP2ztHf/2vVFYU67obx0XucLo5wAoBdwTsHevveW3tEiY6LpyRnJ3lt7REAwLg5dqC3759qjxirjrrnaaC3b2aSD07MGgCgouEkr+5vty4r+YvcMP4IBnr7XpHksnTm2TIAYMfuTfLC/nZr0Vj/AvH0MAZ6+56a5MYk+0/oIACgtl8keclYX+XiCeMPYaC3b0qSL0Q4AUA3OCTJabVHPJLGx1OSmUn6a48AACbNvzT5NS6Nvmw30Nv3W7nv9N30SRkEADTF0iS/3d9urX+kH+Sy3XYGevt6kpwb4QQA3eipSRr5/KfGxlOSN8XlOgDoZm8f6O17Xu0RD9bIeBro7XtMkg/U3gEAVDU1yYdrj3iwRsZTkrfnvtN1AEB3e8Xosx4bo3HxNNDbt1eS2bV3AACNcUrtAdtrXDwl+ad4phMA8N9e0qSzT42Kp4Hevt2S/GvtHQBA48ysPeB+jYqnJK9P8pTaIwCAxnnlQG/fb9cekTQvnt5aewAA0Fh/X3tA0qAnjA/09j0ryfxqYwCApluZ5KD+dmvL/X+i258w/ubaAwCARts/yR/UHtGkeHpD7QEAQONV74VGXLZzyQ4AGKM1SR7f324NJt192e7VtQcAAB1hnyT/s+aApsRT9euXAEDHqNoN1eNpoLdvSpKX1t4BAHSMI2oevHo8JXlu7jsFBwAwFi8e6O3bvdbBmxBPL6o9AADoKHvkvpMvVTQhng6tPQAA6DjV+qEJ8dRXewAA0HGq9UMT4umZtQcAAB2nWj9UjaeB3r6eJE+tuQEA6EjPqHXg2meepiaZVnkDANB5nlLrwLXjqfbxAYDOtH+tA9eOl6mVjw8AdKae0dt/Jl3teKp9fACAIuIFAKBA7XiqfXwAoHN15WW7Kl80AMCjVTueAAA6ingCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAApMqz0AgM7RM21a9j38xdnn8BflMU9/enbb73Hp6empPavxhjZsyObbl2ftTb/I6qt/lG2rV9eexE4QTwDs0NQ998xT/u9f58A3vzG77b9f7Tkd68A/f3NGhoay4nvfz21nn5ONixbXnsSj4LIdAI9o3//xkrzo0m/lae94m3AaBz1Tp+YJr3lVXvjtr+dp73hbeqb6pbjT+CcGwMM64A2vzyGfPjfTn/TE2lN2OT1Tp+Zp7/jn/PaZH8mU6dNrz6GAeALgIT3xta/Jb578rmSKXyom0v4v/1959ukfSNw71jH8FwHAr3nsM5+R33rPSbVndI3H//7L85S//ZvaMxgj8QTAr3nWu47PlD1cSppMT/+Xt2f6AQfUnsEYiCcAfsU+L35h9n3J4bVndJ0pe0zPU9/6t7VnMAbiCYBf8eTX/2ntCV3rSX/8R5my++61Z7AD4gmA/9bTk/2OeGntFV1r6l57Ze8XPr/2DHZAPAHwgD0OPCC7Pe5xtWd0tRnPfW7tCeyAeALgAdMPdMNybdMPeHLtCeyAeALgAVP33Kv2hK43dc/H1p7ADognAB7QM21q7QnQeOIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoMC02gOA5trzN5+VvZ9/WB7ztN/I1BkzMmX33WpP2uWNbBvM4Pr12bzs9qxr3ZJ1N7eS4eHas4DtiCfgV0zZY3oOeOMbcuBb3pjHPO1pted0va0rV+bOCy/Oss99IYNr1tSeA8RlO2A7+/7OS/KiS76Vg485Wjg1xO7775/f+Od/zOGXX5onvvY1tecAEU/AqIP+6i9yyGfOzR4HHVh7Cg9h2t5759kffH8OPv6YpKen9hzoai7bATnwz9+cg4+dVXsGY3DQX7wlSbLwlFMrL4Hu5cwTdLm9X/D8HHzs7NozKPCk//3Hmbb3jNozoGuJJ+hiPbvtlt73npyeqX4q6CTz331yBteuqz0DupafMaGLPfE1r85jnvH02jMocPe3L8k9l3y39gzoauIJutiBb3lj7QkU2Hz78sw/6ZTaM6DriSfoUrs//vGZccjzas9grIaHM/eo2Rlav772Euh64gm61IxDhVMnWfLJT2XtDTfWngFEPEHX2uNAz3PqFOt+cXNuO+uc2jOAUeIJutS0ffauPYExGNq0KXNnzs7I0FDtKcAo8QRdy1OqO8HCU07NpiVLas8AtiOeABpqxfcvz53/+fXaM4AHEU8ADbT17rsz/8STa88AHoJ4AmigubOOzbZ77609A3gI4gmgYZad/7nc+1/X1Z4BPAzxBNAgG9rzcusZZ9aeATwC8QTQEMNbtmTOkUdneOvW2lOARyCeABpi0WkfysYFC2vPAHZAPAE0wKqrrsnyL3+l9gxgDMQTQGXbVq3OvGOOT0ZGak8BxkA8AVQ277gTs3XlytozgDESTwAVLb/gwqz84ZW1ZwAFxBNAJRsXLc6iD5xeewZQSDwBVDAyOJi5M2dlePPm2lOAQuIJoIJbP/KxrP/lnNozfs3GeQsyvHlL7RnQaOIJYJLde91PsvQzn6094yFtWrIki05zKREeiXgCmESDa9emPevYZHi49pSHtfyCC7PqyoHaM6CxxBPAJJp/4knZcuddtWc8spGRtI87MdtWrqq9BBpJPAFMkru+/s3c873v154xJttWrkr72ONrz4BGEk8Ak2Dz0mVZcMqptWcUWTVwdZZ/6YLaM6BxxBPABBsZGs7cmbMytGFD7SnFFn3wQ9m4cFHtGdAo4glggi055xNZe9Mvas94VIY3b8mcI4/OyLZttadAY4gngAm09uc3Zck5n6w9Y6dsmNvO4jPOrD0DGkM8AUyQoQ0bMveo2RkZau5jCcZq2fmfy70/vq72DGgE8QQwQRa859RsXrqs9ozxMTKS9qxjM7hmTe0lUJ14ApgA93z3stz1jW/WnjGuttx1d+adeHLtGVCdeAIYZ1vuvCvz37VrRsaKy76fO7/2jdozoCrxBDCe7r+8tXZt7SUTZuEpp2bTkqW1Z0A14glgHC097/zce91Pas+YUEMbN+4yN8LDoyGeAMbJ+l/Oya1nnlV7xqRYd9MvctvZH689A6oQTwDjYHjzlsydOaurHia59JOfytobf157Bkw68QQwDha+/7RsXLS49oxJNTI0nLlHze7I187AzhBPADtp1ZUDuePCr9aeUcXmZbdnwcnvrT0DJpV4AtgJ21auSvvYE5KRkdpTqrnrm9/OPZd+r/YMmDTTag+gGfb8zWdlr77nZo8DD8i0GTOSKbp6og1v3ZqhdeuzcfGtWXfTTdly1921J/EotI85LttWra49o7r57z45ez//sEw/4Mm1p8CEE09dbNreM3LAm96YA974Z9njoANrz+l6635xc27/4pdzzyWX+hbwDrH8Sxdk1VXX1J7RCINr12Xu0cfk0M992v98scvzb3iXesKrXpkXf/c7ecZ//KtwaogZhzwvzz7t1Dz/4guz13OeXXsOO7BxwcIsOu1DtWc0yprrf5qln/5s7Rkw4cRTt+npycGzj8pzzjg9u+2/X+01PIS9nvPsHHbhl/KE17yq9hQexsi2bZkzc1aGt2ypPaVxbv3ox7L+l3Nqz4AJJZ66zMHHzc5Bf/NXtWewA1N23z3P+eD784Q//IPaU3gIiz/80WyY2649o5FGBgcz58ijM7x5c+0pMGHEUxd58uv/JAf9xVtqz2CspkzJ0//9nbVX8CD3/td1WfbZz9ee0WibFt+ahe//YO0ZMGHEU5fYff/9c/Dso2rPoMTISOa/6z21V7CdwTVr0p59bFc/lmCs7vjKRVn5wytrz4AJIZ66xFP/4e8yda+9as+gwLLPfDb3/vi62jPYzrzj3+2REgXmHXditq5YUXsGjDvx1AWmTJ+eJ/3J62rPoMD6OXOz+CMfqz2D7dx58dey4vIras/oKNtWrc68Y06oPQPGnXjqAvse/uJMm+GsU6foxhfMNt2mJUuz8H0fqD2jI626+prc/oUv1Z4B40o8dYEZhx1aewIFFp12ejYuXFR7BqNGhoYzd+asDG3cWHtKx1p8+hnZuGBB7RkwbjxhvAvs8ZSDak9gjFZdeVWWX3Bh7RlsZ9PixdnviJdlvyNettOfdc+l383GRYvHYdXEmrb3jBz0V385rp+5YcGiPPZZzxrXz4RaxFMXmOZG8Y6wbeWqtI/r7hfMNtFjn3VwnvaOt43LZ62fO7cz4mnGjHH7mmFX5LIdNET72OOzbeWq2jMA2AHxBA2w/EsXZNXA1bVnADAG4gkq27hwURZ90AtmATqFeIKKRrZty9yZszK82QtmATqFeIKKFp9xZtbPmVt7BgAFxBNUcu+Pr8uy8z9XewYAhcQTVDC4Zk3as7xgFqATiSeoYN6JJ3vBLECHEk8wye782jey4rLv154BwKMknmASbVqyNAtPObX2DAB2gniCSTIyNJy5R832glmADieeYJLcdvbHs+6mX9SeAcBOEk8wCdbe+PMs/eSnas8AYByIJ5hgQxs2ZO5RszMyNFx7CgDjQDzBBJt/0inZvOz22jN+zZbly2tPAOhI4gkm0D2Xfi93f+s7tWc8pDu//s2s/tG1tWcAdBzxBBNkyx13ZP67T6494+GNjKQ9+/hsW7269hKAjiKeYCIMD2fu0cdmcO262kse0dZ77sm8499VewZARxFPMAGWnveZrLn+p7VnjMnK//fD3HHRxbVnAHQM8QTjbP0tv8ytZ55de0aRRaeelk233lZ7BkBHEE8wjoY3b86cI4/OyOBg7SlFhjZtytyZszIyNFR7CkDjiScYRwvf94GOPYOzrnVLbv3oWbVnADSeeIJxsvIHnX/v0LJPfyZrrv9Z7RkAjSaeYBxsXbEi847r/O9aGxkaztyjj8nguvW1pwA0lniCcbArPS+p8c+nAqhMPMFOuv3zX8zqa35Ue8a4uueS7+bub19SewZAI4kn2Akb5s3P4g99pPaMCTH/pFOy2fvvAH6NeIJHaXjr1sw9anaGt2ypPWVCDK1fn7kzZyfDw7WnADSKeIJHafGHPpIN7Xm1Z0yotTfcmCXnnld7BkCjiCd4FFb/6Nrc/vkv1p4xKW772Mez7uZW7RkAjSGeoNC2e+9N+5gTkpGR2lMmxcjQUOYeOStDmzbVngLQCOIJCs07/l3ZevfdtWdMqk1LlmThe99fewZAI4gnKHDHRRdn5RU/qD2jijsv/lpWXH5F7RkA1YknGKNNt92WRaeeVntGVfNPOKnrzroBPJh4gjFw3899tt17b9qzj6s9A6Aq8QRjcNuZZ2dd65baMxph9bU/zrLzP197BkA14gl2YM1Pb8jS8z5de0aj3HrGR3f5Z1wBPBzxBI9gcN36tI8+JiNDnrK9veGtWzPnyKMzvHVr7SkAk048wSNYcNJ7vN/tYWxcsDCLPnB67RkAk048wcO4+9uX5O7vXFp7RqMt//JXsurqa2rPAJhU4gkewubly7Pg5FNqz2i+kZHMm318tq1eXXsJwKQRT/Bgw8NpH3VMBtetr72kI2xduTLzjj2x9gyASSOe4EGWnHte1vzshtozOsrKH16ZOy78au0ZAJNCPMF21t3cym1nnVN7RkdaeOpp2bhoce0ZABNOPMGooU2bMnfm7IwMDtae0pGGN2/O3Jmz/P0DdnnTag+Aplhz3fXZ+wWHZe8XHLbTn7XisssztHHjzo+aYNMPOCD7/s7h4/qZa264Mfse/uJx/UyAJhFPMGq/3z0i+/3uEePyWWt+cn1HxNNez31Oek/1XYUAJVy2AwAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIJwCAAuIJAKCAeAIAKCCeAAAKiCcAgALiCQCggHgCACggngAACognAIAC4gkAoIB4AgAoIJ4AAAqIpy4wvGVL7QkAjNHQho21J7AD4qkLbLnjjtoTABijLXfeWXsCOyCeusC6X86pPQGAMVp/yy9rT2AHxFMXWH3NtRkZHKw9A4AdGFq/PmtuuLH2DHZAPHWBwTVrsuKKH9SeQRMNj9ReQAONDA3VntC17vr2JRne7D7VphNPXWLJJ87NyNBw7Rk0zOprr82Wu+6uPYOG2XLnXVn9o2trz+g6w1u3Ztl5n6k9gzEQT11iw9x2bv/8F2rPoGGGN2/Jgve8t/YMGmjBKadmaNOm2jO6ym1nfTybb19eewZjIJ66yOIPfzRrrv9Z7Rk0zMorfpBl53+u9gwaZtPiWzP/hHfXntE1Vv7gh1l63vm1ZzBG4qmLjGzbllv++R1Z89Mbak+hYRad9qEs//JXas+gYe7+zqWZ/+73JMMu+U+kVVddkzn/cbS/zx1EPHWZwXXrc/PfvjW3f/HLyYibhRk1MpIFJ7838054t5tV+RV3fOWi3PTXf+feuAkwMjScJed8Mre87R0Z3ry59hwKiKcuNLx1axaecmpufMNbsuqqa0QUD7jzq/+Zn/zBq3PHRRf7yZwHrLn+p/npq16b2846J9tWrqo9p+ONDA1nxeVX5IbXvT63fvQs393YgXpGKv7CedWzn7d3kjXVBpAkmf7kJ2W/I16WGYc8L9MPPDBTdptWe1LHm/PvR2XrihW1Z+yUqXvumf2OeGn2PuzQ7PEbT820vfaqPanj3fqRj2XNzzr7snnPtGl53P/4nez9wufnsQc/M9P22Sc9PT21ZzXe8LbBbF62LOt+flNWXXVNx//80CBTj5h786Rf7xRPAECnqhJPLtsBABQQTwAABcQTAEAB8QQAUEA8AQAUEE8AAAXEEwBAAfEEAFBAPAEAFBBPAAAFxBMAQAHxBABQQDwBABQQTwAABcQTAEAB8QQAUEA8AQAUEE8AAAXEEwBAAfEEAFCgdjyNVD4+AECR2vE0XPn4AEDnqnISpnY8AQB0lNrx5LIdANBRasfTUOXjAwAdqr/d6srLduIJAHg0Vtc6cBPiyaU7AKDUHbUOXDWeRk+3La+5AQDoSItrHbj2maek4hcPAHSsro6nVu0BAEDHqdYPTYinm2sPAAA6TrV+aEI8/az2AACgowwluanWwZsQTzck2VR7BADQMW7sb7c21Dp49Xjqb7e2JflJ7R0AQMf4Uc2DV4+nUZfXHgAAdIyq3dCUePpu7QEAQEfYkuSHNQc0JZ5uTLK09ggAoPEu72+3NtYc0Ih4Gn3S+Fdr7wAAGu+i2gMaEU+jvlJ7AADQaJuSfKv2iMbEU3+7dX0qPrMBAGi8i/rbrTW1RzQmnkZ9uvYAAKCxGtEJTYun85NUL0oAoHF+1t9uXV17RNKweOpvt9YnObf2DgCgcT5ce8D9GhVPo85Isrn2CACgMRamAd9ld7/GxVN/u3VHko/X3gEANMZJ/e3WYO0R92tcPI06Ncna2iMAgOpaSb5Ue8T2GhlP/e3WiiQn194BAFT37/3t1nDtEdtrZDyN+liSubVHAADVfK2/3bqi9ogHa2w89bdbW5P8Y+0dAEAV65K8s/aIh9LYeEqS/nbrqiTn1N4BAEy6mf3t1u21RzyURsfTqKOSzKs9AgCYNN9J8qnaIx5Oz8jISL2D9/SM6ccN9Pa9IMl/Jdl9QgcBALXdkeTQ/nbrnrH84Bod0wlnntLfbt2Qhl73BADGzWCSN4w1nGrpiHhKkv5265NJzqu9AwCYMP/W325dU3vEjnRMPI16e5LGfcsiALDTzuxvt86uPWIsOiqeRh9f8PokN9feAgCMm28k+Y/aI8aqo+IpSfrbrTVJXp6kXXsLALDTvpfkjf3t1lDtIWPVcfGUJKM3kr0iAgoAOtnlSf509MpSx+jIeEqS/nZrWZKXxSU8AOhE30ryR/3t1sbaQ0p1bDwlD5yBelncRA4AneQTSf6k08443a8jHpK5IwO9fbsnOTvJ34/LBwIAE2E4yaz+duv08frAGh2zS8TT/QZ6+96a5Kx4EjkANM3KJG/qb7fG9WqReBoHo69yuSDJb437hwMAj8aVSf5y9H7lceX1LONg9FUuL0hyTu0tANDltiSZleTlExFOtexyZ562N9Db97Ik5yZ59oQeCAB4sCuT/EN/uzV/Ig/izNM462+3rk5yaJIjk6ytPAcAusHSJG9K8nsTHU617NJnnrY30Nv3+CSzc9/78faYtAMDQHdYmeR9Sc7pb7c2TdZB3TA+CQZ6+w5I8m9J/jHJPpM+AAB2LUuTnJnkE/3t1vrJPrh4mkQDvX17Jfmb3PdsqEOrDQGAzvSDJJ9KcnF/uzVYa4R4qmSgt+/Fue/67J8leWrlOQDQVK0kFyW5oL/dWlB7TCKeqhvo7etJcliSP0zyyiSHJ3lMzU0AUNG9Sa5JclmS7zUlmLYnnhpmoLdvt9z3zKgXJDkkyXOTPDPJgUmaPR4Axm4w9927tDD3nV26Kcn1Seb0t1vDNYftiHjqEKNnqKZu99v9X8iUiCoAmmsk971fLqO/H0oyXPOepZ3VdfEEANBpdumHZAIAjDfxBABQQDwBABQQTwAABcQTAEAB8QQAUEA8AQAUEE8AAAXEEwBAAfEEAFBAPAEAFBBPAAAFxBMAQAHxBABQQDwBABQQTwAABcQTAEAB8QQAUEA8AQAUEE8AAAXEEwBAAfEEAFBAPAEAFBBPAAAFxBMAQAHxBABQQDwBABQQTwAABcQTAEAB8QQAUEA8AQAU+P+j87IVkkwV4gAAAABJRU5ErkJggg=="
              loading="lazy"
              className="hidden w-[128px] object-contain md:block"
              alt=""
            />
            <div className="flex flex-col ">
              <p className="text-2xl font-black">COMPOUNDING REWARDS</p>
              <p className="text-2xl font-light">
                50% of all rewards will be compounded, so the giveaway grows
                more and more each week!
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Tokenomics
