export const data = {
  bulls: {
    tokenomics: [
      {
        title: "TICKET TO REWARDS",
        description:
          "By accumulating Bullion, holders of TR Bulls are granted exclusive access to rewards generated by our varied investment portfolio. Think of a TR Bull as your personal Bullion producer and a means to unlock these benefits.",
        src: "/Icons/RaffleTicket.svg",
      },
      {
        title: "MEMBERSHIP",
        src: "/Icons/MembershipIdea.svg",
        description:
          "Owning a BTC Bull NFT means you're a valued member of our community, with no additional monthly or yearly fees required to maintain your membership in the TR  Bulls Community or the future of The Ranch ecosystem.",
      },
      {
        title: "RARITY",
        src: "/Icons/FrogsTurtles.svg",
        description:
          "Rarity is present in The Ranch Bulls NFT Collection through two unique variations of the regular TR Bulls: Bulls paired with Frogs or Turtles. Among the two, a TR Bull with a Frog is deemed the scarcer one, as there are only 8 frogs in the collection compared to 11 turtles. These distinct NFTs receive a bonus USDC airdrop at the start and an enduring advantage of producing more Bullion per month than the regular TR Bull NFTs.",
      },
      {
        title: "REINVESTMENT",
        src: "/Icons/CompoundingIllustration.svg",
        description:
          "Through reinvestment, our community will collectively determine the next venture to allocate a portion of our investment profits. This continuous process enables us to broaden our portfolio with varied investments both in and out of web3, fostering growth as a community.",
      },
      {
        title: "BUDDY SYSTEM",
        src: "/Icons/BuddySystem.svg",
        description:
          "Our buddy system is a unique referral program that offers a lifetime benefit to our community members. Simply refer a buddy to the project who mints, and you'll earn 2% of all rewards earned by your referred buddy in the project for the lifetime of the project.",
      },
      {
        title: "Verify",
        src: "/Icons/Verify.svg",
        description:
          "Each TR Bulls NFT provides access to a token-gated part of the website to view access reports, treasury balance, and the club portfolio.",
      },
    ],
  },
  bears: {
    tokenomics: [
      {
        title: "TICKET TO REWARDS",
        description:
          "1 BTC Bears = one share of the monthly profits from the Community Bitcoin Mining Cluster.",
        src: "/Icons/RaffleTicket.svg",
      },
      {
        title: "REINVESTMENT",
        src: "/Icons/CompoundingIllustration.svg",
        description:
          "1/3 of all monthly mining rewards are reinvested to grow our BTC mining cluster now, with the community voting on when to switch to a zero reinvestment model to capitalize on BTC price during the next Bull Market.",
      },
      {
        title: "BUDDY SYSTEM",
        src: "/Icons/BuddySystem.svg",
        description:
          "A single-level referral system. Helping to grow the community rightfully rewards you.",
      },
      {
        src: "/Icons/RaffleDrawingMachine.svg",
        title: "Weekly Minting Giveaway",
        description:
          "3% of all minting transactions will be used in a weekly Minting giveaway to award $590 to as many people as the balance allows. ",
      },
      {
        title: "Early Supporters (ES)",
        src: "/Icons/EarlySupporter.svg",
        description:
          "Early bird gets the worm as they say. Early Supporters of the ecosystem get access to the  Royalty Rewards Program and future perks as the ecosystem continues building out. ",
      },
      {
        title: "Verify",
        src: "/Icons/Verify.svg",
        description: "Access reports, treasury balance and club portfolio. ",
      },
      {
        title: "Claim",
        src: "/Icons/Claim.svg",
        description: "Claim all rewards directly from the site from day one. ",
      },
      {
        title: "Vote",
        src: "/Icons/Voting.svg",
        description:
          "Community members can vote on the direction of the project and their community.",
      },
    ],
  },
};
