export const data = {
  bulls: {
    tokenomics: [
      {
        title: "TICKET TO REWARDS",
        description:
          "By accumulating Bullion, holders of TR Bulls are granted exclusive access to rewards generated by our varied investment portfolio. Think of a TR Bull as your personal Bullion producer and a means to unlock these benefits.",
        src: "/Icons/RaffleTicket.svg",
      },
      {
        title: "MEMBERSHIP",
        src: "/Icons/MembershipIdea.svg",
        description:
          "Owning a BTC Bull NFT means you're a valued member of our community, with no additional monthly or yearly fees required to maintain your membership in the TR  Bulls Community or the future of The Ranch ecosystem.",
      },
      {
        title: "RARITY",
        src: "/Icons/FrogsTurtles.svg",
        description:
          "Rarity is present in The Ranch Bulls NFT Collection through two unique variations of the regular TR Bulls: Bulls paired with Frogs or Turtles. Among the two, a TR Bull with a Frog is deemed the scarcer one, as there are only 8 frogs in the collection compared to 11 turtles. These distinct NFTs receive a bonus USDC airdrop at the start and an enduring advantage of producing more Bullion per month than the regular TR Bull NFTs.",
      },
      {
        title: "REINVESTMENT",
        src: "/Icons/CompoundingIllustration.svg",
        description:
          "Through reinvestment, our community will collectively determine the next venture to allocate a portion of our investment profits. This continuous process enables us to broaden our portfolio with varied investments both in and out of web3, fostering growth as a community.",
      },

      {
        title: "Verify",
        src: "/Icons/Verify.svg",
        description:
          "Each TR Bulls NFT provides access to a token-gated part of the website to view access reports, treasury balance, and the club portfolio.",
      },
    ],
  },
};
